// src/config.js
const BASE_URL_API = process.env.REACT_APP_API_URL;
const BASE_URL_DEV_API = process.env.REACT_APP_DEV_API_URL;
const NOVATIDE_URL_API = process.env.REACT_APP_NOVATIDE_URL_API;
const BOTS_V2 = process.env.REACT_APP_V2_API;
const BOTS_V2_DEV = process.env.REACT_APP_V2_DEV_API;
const ACCESS_KEY_AWS = process.env.REACT_APP_AWS_ACCESS_KEY_ID
const SECRET_ACCESS_KEY_AWS = process.env.REACT_APP_AWS_SECRET_ACCESS_KEY
const AWS_REGION = process.env.REACT_APP_AWS_REGION
const AWS_ICONS = process.env.REACT_APP_AWS_ICONS_BUCKET
const X_API_KEY = process.env.REACT_APP_X_API_KEY
const X_API_KEY_DEV = process.env.REACT_APP_X_API_KEY_DEV
//config server
const config = {
   BASE_URL:  BASE_URL_API,
   BASE_URL_DEV: BASE_URL_DEV_API,
   NOVATIDE_URL: NOVATIDE_URL_API,
   BOTS_V2_API: BOTS_V2,
   BOTS_V2_DEV_API: BOTS_V2_DEV,
   AWS_ACCESS: ACCESS_KEY_AWS,
   AWS_SECRET_ACCESS: SECRET_ACCESS_KEY_AWS,
   AWS_REGION: AWS_REGION,
   S3_BUCKET: AWS_ICONS,
   X_API_KEY: X_API_KEY,
   X_API_KEY_DEV: X_API_KEY_DEV,
}
export default config